CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Turn on Pokémon animation instead of cat
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_POKEMON=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
