# Uncomment the following lines to enable the Corne RGB Underglow

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_DISPLAY=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=y
CONFIG_NICE_OLED_POKEMON_ANIMATION=y
